CREATE TABLE [dbo].[Categories]
(
	[Id] INT NOT NULL IDENTITY,
	[Name] NVARCHAR(250) NOT NULL,	
	[CreDate] DATETIME NOT NULL DEFAULT GETDATE(),
    [IsActive] BIT NOT NULL DEFAULT 1,
	CONSTRAINT [PK_CATEGORIES] PRIMARY KEY ([Id])
)
